// サンプル案件20件（各段階に散らす）を JSON に書き出す。共有DBへは Artifact の write_db(batch) で入れる。
const fs = require('fs'); const path = require('path');
const OUT = path.join(__dirname, 'seed'); fs.mkdirSync(OUT, { recursive: true });
const DAY = 86400000; const NOW = Date.now();
const SEATS = ['OWN','BUILD','SELL','SITE','BUY','ACC'];
const S = (k,t,n)=>({t,n:n||'',since:NOW-5*DAY});
const base = (o) => ({
  title:o.title, benefit:o.benefit, demo:o.demo||'', owner:o.owner, createdAt:NOW-o.age*DAY, stage:o.stage, domain:o.domain,
  reframed:o.reframed, firstMove:o.first, payers:o.payers, lines:o.lines,
  seats:{OWN:S('OWN','hu',o.owner),BUILD:o.build?S('BUILD','hu',o.build):S('BUILD','ai','AIが準備中'),SELL:o.sell?S('SELL','hu',o.sell):S('SELL','ai','AIが準備中'),SITE:o.site?S('SITE','hu',o.site):S('SITE','em'),BUY:o.buy?S('BUY','hu',o.buy):S('BUY','em'),ACC:o.acc?S('ACC','hu',o.acc):S('ACC','em')},
  actions:(o.actions||[]).map((a,i)=>({id:'a'+i,seat:a[0],text:a[1],due:NOW+(a[2]||7)*DAY,state:a[3]||'open',by:'AI'})),
  bids:(o.bids||[]).map((b,i)=>({id:'b'+i,seat:b[0],by:b[1],text:b[2],price:b[3],days:b[4]||7,won:!!b[5],t:NOW-(o.age-1)*DAY})),
  messages:(o.msgs||[]).map((m,i)=>({by:m[0],text:m[1],t:NOW-(o.age-1)*DAY+i*3600000})),
  cf:o.cf||null, fund:o.fund||null,
  criteria:(o.criteria||[]).map((t,i)=>({id:'k'+i,text:t})), criteriaLocked:!!(o.bids||[]).some(b=>b[5]),
  deliveries:(o.deliveries||[]).map((d,i)=>({id:'d'+i,version:i+1,note:d[0],diff:d[1]||'',by:d[2],t:NOW-(o.age-3)*DAY+i*DAY,rejected:!!d[3],reason:d[3]||'',accepted:!!d[4]})),
  checks:[], ledger:[], notices:[], receipt:o.receipt?{amount:o.receipt,by:o.owner,t:NOW-DAY,mock:true}:null,
  dist:o.dist?{price:o.dist,fixed:Math.round(o.dist*0.5),perf:30,idea:10,fee:Math.min(4500,Math.round(o.dist*0.15)),units:['u1','u2'],proposedAt:NOW-(o.distDays||1)*DAY,rows:[]}:null,
  objections:o.objections||[], likes:o.likes||[], archived:false,
  log:[{t:NOW-o.age*DAY,m:o.owner+' が「もし」を置いた'},{t:NOW-o.age*DAY+60000,m:'AI席が最初の一手を返した。作る席と売る席で準備を開始'}].concat((o.log||[]).map((m,i)=>({t:NOW-(o.age-1)*DAY+i*3600000,m}))),
  measurement:{stage2At:o.stage>=2?NOW-(o.age-2)*DAY:null,acceptedAt:o.stage>=4?NOW-(o.age-4)*DAY:null,settledAt:o.stage>=5?NOW-1*DAY:null,realCreatedAt:NOW-o.age*DAY,realStage2At:o.stage>=2?NOW-(o.age-2)*DAY:null,realAcceptedAt:o.stage>=4?NOW-(o.age-4)*DAY:null,realSettledAt:o.stage>=5?NOW-DAY:null,testClockUsed:false,activeMinutes:o.minutes??null,effortBasis:o.minutes!=null?'measured':'estimated',sameBenefit:'unconfirmed',comparisonNote:'',aiCost:{amount:o.ai??null,basis:o.ai!=null?'measured':'unknown'},materialCost:{amount:o.mt??null,basis:o.mt!=null?'measured':'unknown'}},
  sample:true,
});
const L = {
  pet:['健康・栄養に関わる提案は薬機法と景品表示法の線がある。「参考値」の姿勢を通す（専門家に確認）','犬の健康記録は飼い主の個人情報と一緒に動く。物販側に渡す範囲を先に決める'],
  labor:['受任の範囲は手続きと代理まで。会社との交渉は弁護士のみ（確認）','給付金の表示は概算に留め「必ずもらえる」と読める表現を避ける'],
  travel:['提案までなら自由。予約の手配まで踏み込むと旅行業の登録が要る（確認）'],
  care:['要介護者の情報は要配慮個人情報。施設との契約で扱いを決める','医療行為・診断に当たる表現をしない'],
  food:['食品を扱う場合は営業許可・表示の確認','アレルギー表示は必須'],
  edu:['未成年が関わる場合は保護者同意の設計が先'],
  local:['自治会名・実在団体名を出さない。個人情報は集計値のみ'],
};
const cases = [
 // 段階0：投稿（5）
 {id:'s01',title:'もし、洗濯物をたたむだけの人が近所にいたら',benefit:'共働きの家庭',owner:'例：さくら',age:2,stage:0,domain:'家事',reframed:'もし、家事の一部だけを近所に頼めたら',first:'便益を受けるのは共働きの家庭。払うのも本人ですが、1回いくらなら頼むかが本体です。家事代行の全部ではなく「たたむ」だけを切り出す点が違い。まず10世帯に「月にいくらまで」を聞きます。',payers:['家庭本人（都度払い）','マンション管理組合（共用サービス）','家事代行事業者（送客）'],lines:['家に入る作業は保険と本人確認の線がある'],actions:[['OWN','10世帯に「たたむだけ」なら月いくらまでか聞く',7],['SELL','近所の主婦・学生に手を挙げてもらう募集文を作る',5],['SITE','受け渡し場所（管理人室・宅配ボックス）の候補を出す',7]],likes:['例：ゆき','例：けん']},
 {id:'s02',title:'もし、町内会の回覧板がスマホで済んだら',benefit:'回覧を回す班長',owner:'例：たかし',age:9,stage:0,domain:'地域',reframed:'もし、回覧が回さなくても届いたら',first:'便益を受けるのは班長と回覧を待つ世帯。払うのは自治会か市区町村。個人が払う理由が薄いので、自治会の年会費から出せる額が上限になります。まず自治会1つに「紙代と手間」を数字で出してもらいます。',payers:['自治会（年会費から）','市区町村（地域振興）','地域の印刷会社（紙からの移行支援）'],lines:L.local,actions:[['OWN','自治会1つに紙代と配布の手間を数字で出してもらう',7],['BUILD','LINE公式だけで回る最小の形を試作する',10]]},
 {id:'s03',title:'もし、子どもの絵をそのまま絵本にできたら',benefit:'幼児の親',owner:'例：みほ',age:12,stage:0,domain:'子ども',reframed:'もし、描いた絵がその日のうちに絵本になったら',first:'便益を受けるのは親と祖父母。払うのは祖父母が多い。物としての絵本（印刷）が本体で、アプリは入口です。まず1冊いくらなら祖父母が買うかを確かめます。',payers:['祖父母（贈り物）','親','幼稚園・保育園（卒園記念）'],lines:L.edu,actions:[['SELL','祖父母10人に1冊いくらなら買うか聞く',7],['BUILD','印刷所の最小ロットと単価を調べる',5]]},
 {id:'s04',title:'もし、介護施設の夜勤の申し送りが声で済んだら',benefit:'夜勤の介護職',owner:'例：のぞみ',age:3,stage:0,domain:'介護',reframed:'もし、申し送りを声で残して朝に読めたら',first:'便益を受けるのは夜勤の職員と朝勤の職員。払うのは施設。施設が払う理由は記録の質と残業の減少。まず1施設で夜勤1回分の申し送りにかかる時間を測ります。',payers:['介護施設（業務改善）','施設運営法人','介護ソフト事業者（連携）'],lines:L.care,actions:[['OWN','1施設で申し送りにかかる時間を測る',7],['BUILD','音声→要約の最小の形を試作',10],['ACC','施設長に「読める記録」の基準を出してもらう',7]],likes:['例：けん','例：さくら','例：りょう','例：あき']},
 {id:'s05',title:'もし、地元の畑の余り野菜が当日中に近所に届いたら',benefit:'近所の家庭と農家',owner:'例：りょう',age:1,stage:0,domain:'食',reframed:'もし、余った野菜がその日のうちに近所で売れたら',first:'便益を受けるのは農家と近所の家庭。払うのは家庭。届ける人と場所が本体です。まず農家2軒に週にどれだけ余るかを聞きます。',payers:['家庭（都度）','飲食店（仕入れ）','スーパー（地場コーナー）'],lines:L.food,actions:[['OWN','農家2軒に週の余りを聞く',5],['SITE','受け取り場所（公民館・店先）の候補',7],['SELL','近所30世帯に「届いたら買うか」を聞く',7]]},
 // 段階1：形あり（4）
 {id:'s06',title:'もし、散歩と食事の記録から、うちの子に合ったフードが提案されて、そのまま届いたら',benefit:'愛犬の食事と散歩に迷う飼い主',owner:'例：A',age:6,stage:1,domain:'ペット・物販',demo:'https://example.invalid/dog/',reframed:'もし、記録からうちの子に合うフードが届いたら',first:'便益を受けるのは飼い主。払うのも飼い主本人ですが、アプリにではなくフードに払います。本体は物販、アプリは入口。まず飼い主30人のうち何人が提案フードを買うかを確かめます。',payers:['飼い主本人（フード・サプリの物販）','動物病院・トリミング店','ペット保険・食品メーカー'],lines:L.pet,build:'例：A',actions:[['OWN','達成条件を一行で決める（30人中、何人が買ったか）',7],['SELL','Bさんが「何を持っているか」を書いて座る',7],['BUILD','提案ロジックにフードの一覧をつなぐ',14]],bids:[['SELL','AI','飼い主向けの案内文3案と購入導線の下書き。価格・仕入れ・発送条件は未確認。',0,0,false]],criteria:['飼い主30人が4週間記録できる','提案フードの購入導線がある','個別データを物販側に渡さない'],likes:['例：B','例：ゆき']},
 {id:'s07',title:'もし、辞める前に「いくらもらえて、何をすればいいか」が分かって、そのまま手続きを頼めたら',benefit:'退職を考えている人',owner:'例：A',age:6,stage:1,domain:'手続き・受任',demo:'https://example.invalid/taishoku/',reframed:'もし、辞める前に手続きまで頼めたら',first:'便益を受けるのは退職を考えている人。払うのも本人で、サービスは手続きの代行。診断が入口、マニュアルが低額商品、受任が本体。3件でいちばん早く一周します。',payers:['退職者本人','転職エージェント（送客）','企業の人事（退職支援）'],lines:L.labor,build:'例：A',sell:'例：Dさん',actions:[['SELL','受任の範囲を決めて、サイトの文言を直す',7],['BUILD','診断結果から「あなたの手順」に落ちるマニュアルを1本',14],['BUY','診断した人のうち、頼んだ人を数える（4週間）',28]],criteria:['受任範囲がサイトに明記されている','診断→マニュアル→受任の3段が動く','「必ずもらえる」と読める表現がない'],likes:['例：ゆき']},
 {id:'s08',title:'もし、家族の「したい」を入れるだけで、無理のない旅程が出て、そのまま予約できたら',benefit:'子連れの家族',owner:'例：C',age:6,stage:1,domain:'旅行',demo:'https://example.invalid/travel/',reframed:'もし、家族の“したい”がそのまま旅程になったら',first:'便益を受けるのは家族。払うのが家族なのか、旅行会社や宿なのかで、作るものが半分になります。提案までなら自由、予約までなら旅行業の登録が要る。まず分かれ道を決めます。',payers:['家族（アフィリエイト）','旅行会社（入口の提供）','宿・体験事業者（送客）'],lines:L.travel,build:'例：C',actions:[['OWN','提案までか、予約までかを決める',7],['SELL','決めた側に合わせて買い手候補を並べる',3],['BUILD','沖縄1か所に絞って家族10組に使ってもらう',21]],criteria:['沖縄1か所で家族10組が旅程を作れる','予約は外部リンクで行い、自前で手配しない']},
 {id:'s09',title:'もし、冷蔵庫を撮るだけで献立が決まって、栄養も分かったら',benefit:'夜に料理する一人暮らしの人',owner:'例：E',age:15,stage:1,domain:'食・健康',demo:'デモあり',reframed:'もし、冷蔵庫の写真から今夜の献立と栄養が出たら',first:'便益を受けるのは料理する本人。払うのは企業の福利厚生か、スーパー。個人はアプリに払いにくい。まず1社に4週間パッケージで発注意思を確認します。',payers:['企業の福利厚生（健康経営）','スーパー（チラシ連動）','栄養士（監修料の逆）'],lines:L.food,build:'例：E',sell:'例：F',actions:[['SELL','企業1社に4週間パッケージ（仮 30万円）の発注意思を確認',14],['BUILD','栄養の表示を「参考値」にそろえる',7]],bids:[['SELL','例：F','福利厚生担当の知人が2社いる。導入会の会場も出せる',0,14,true]],criteria:['社員20人が4週間使える','栄養の表示が参考値と明記されている','個別データを会社に渡さない'],likes:['例：ゆき','例：けん','例：さくら']},
 // 段階2：買い手あり（4）
 {id:'s10',title:'もし、保育園の連絡帳が写真1枚で済んだら',benefit:'保育士と親',owner:'例：ゆき',age:10,stage:2,domain:'子ども',reframed:'もし、連絡帳が写真と一言で済んだら',first:'便益を受けるのは保育士と親。払うのは園。園が払う理由は保育士の残業。まず1園で連絡帳にかかる時間を測り、園長に発注意思を確認します。',payers:['保育園（運営法人）','自治体（ICT補助）','保育ICT事業者（連携）'],lines:L.edu,build:'例：けん',buy:'例：サンプル園（園長）',actions:[['BUILD','写真＋一言→連絡帳の形式に変換する最小の形',10],['ACC','園長に「読める連絡帳」の基準を出してもらう',5]],bids:[['BUILD','例：けん','LINE公式とスプレッドシートで1週間で試作できる',30000,10,true]],criteria:['保育士が1人1日5分以内で書ける','親が当日中に読める','写真は園の端末にしか残らない'],msgs:[['例：ゆき','園長に確認しました。10月から1クラスで試したいそうです'],['例：けん','了解。今週中に試作を出します']]},
 {id:'s11',title:'もし、地域の空き店舗で週末だけ子ども食堂ができたら',benefit:'ひとり親の家庭',owner:'例：あき',age:20,stage:2,domain:'食・地域',reframed:'もし、週末だけの子ども食堂が空き店舗で回ったら',first:'便益を受けるのは家庭。払うのは家庭ではなく、店舗のオーナーと地元企業。場所と食材の席が本体。まず空き店舗1つの週末利用の条件を確かめます。',payers:['地元企業（協賛）','店舗オーナー（空き活用）','社会福祉協議会'],lines:L.food,build:'例：あき',site:'例：田中（店舗オーナー）',buy:'例：地元商店会',actions:[['SELL','協賛企業3社に声をかける',14],['SITE','保健所の営業許可の要否を確認',7]],bids:[['SITE','例：田中','土日は空いている。光熱費実費のみで貸せる',8000,0,true]],criteria:['土日各1回、30食を提供できる','保健所の確認が取れている','食材の出所が記録されている'],cf:{goal:60000,unit:3000,deadline:NOW+12*DAY,ret:'初回の食事券2枚と活動報告',pledges:[{by:'例：さくら',amount:3000,t:NOW-3*DAY},{by:'例：りょう',amount:6000,t:NOW-2*DAY},{by:'例：ゆき',amount:3000,t:NOW-DAY}],open:true,startedAt:NOW-5*DAY}},
 {id:'s12',title:'もし、社員の残業を「今月あと何時間」で見える化できたら',benefit:'中小企業の総務',owner:'例：Dさん',age:14,stage:2,domain:'労務',reframed:'もし、残業の残り時間が毎朝分かったら',first:'便益を受けるのは総務と本人。払うのは企業。36協定の上限管理が本体。まず1社に月額の発注意思を確認します。',payers:['企業（総務）','社労士事務所（顧問先へ）','勤怠ソフト事業者（連携）'],lines:['勤怠データは個人情報。集計値のみ表示'],build:'例：E',buy:'例：サンプル商事（総務）',actions:[['BUILD','勤怠CSV→残り時間の一覧に変換',7],['ACC','総務に「合っている」と言える確認方法を出してもらう',5]],bids:[['BUILD','例：E','CSV取り込みは既存の部品がある。3日で出せる',20000,5,true]],criteria:['前月のCSVで残り時間が総務の手計算と一致する','個人別の画面は本人と総務だけが見られる'],likes:['例：けん']},
 {id:'s13',title:'もし、地域の小さな商店の「今日のおすすめ」が一つの画面で見られたら',benefit:'商店街の客と店',owner:'例：F',age:8,stage:2,domain:'地域・物販',reframed:'もし、商店街の今日が一画面で分かったら',first:'便益を受けるのは客と店。払うのは商店会。店が個別に払うのは難しい。まず商店会に月額の発注意思を確認します。',payers:['商店会','自治体（商店街振興）','地域メディア'],lines:L.local,build:'例：けん',sell:'例：F',buy:'例：サンプル商店会',actions:[['BUILD','店がLINEで送った写真がそのまま並ぶ形',7],['SELL','商店会の総会で説明',10]],bids:[['BUILD','例：けん','LINE公式の受信をそのまま一覧に。2日',15000,3,true]],criteria:['店が写真を送るだけで載る','当日分だけが表示される'],fund:{goal:100000,unit:10000,deadline:NOW+30*DAY,share:15,use:'初期構築5万円、商店会向け説明会2万円、3か月の運用3万円',pledges:[{by:'例：田中',amount:20000,t:NOW-2*DAY}],open:true,startedAt:NOW-4*DAY}},
 // 段階3：納品（3）
 {id:'s14',title:'もし、訪問看護の移動時間が自動で最短になったら',benefit:'訪問看護師',owner:'例：のぞみ',age:25,stage:3,domain:'介護・医療',reframed:'もし、訪問の順番が毎朝最短で組まれたら',first:'便益を受けるのは看護師。払うのはステーション。移動時間の削減がそのまま訪問件数になる。まず1ステーションで1週間の移動時間を測ります。',payers:['訪問看護ステーション','医療法人','訪問系ソフト事業者'],lines:L.care,build:'例：E',buy:'例：サンプル訪問看護（管理者）',acc:'例：管理者 佐藤',actions:[['ACC','1週間分の訪問記録で検収',7]],bids:[['BUILD','例：E','住所の一覧から順番を出す部分は動いている。地図の表示は後',40000,14,true]],criteria:['1週間分の訪問で移動時間が手組みより短い','順番の変更が当日でもできる','患者の住所は端末の外に出ない'],deliveries:[['https://example.invalid/route-v1','','例：E']],msgs:[['例：E','v1を納品しました。順番の変更は画面右上です'],['例：管理者 佐藤','今週の記録で確認します']]},
 {id:'s15',title:'もし、学童の「今日あったこと」が親に一言で届いたら',benefit:'学童に預ける親',owner:'例：ひろ',age:18,stage:3,domain:'子ども',reframed:'もし、学童の一日が親に一言で届いたら',first:'便益を受けるのは親と指導員。払うのは学童の運営。まず1施設で試します。',payers:['学童の運営法人','自治体','保護者会'],lines:L.edu,build:'例：けん',buy:'例：サンプル学童',acc:'例：指導員 木村',actions:[['ACC','1週間分で検収',7]],bids:[['BUILD','例：けん','保育園の連絡帳の型をそのまま使える。1週間',25000,7,true]],criteria:['指導員が1日5分以内で送れる','親が当日中に読める'],deliveries:[['https://example.invalid/gakudo-v1','','例：けん','写真の向きが直っていない'],['https://example.invalid/gakudo-v2','写真の向きを自動で直した。送信の確認画面を足した','例：けん']],msgs:[['例：指導員 木村','写真が横になります'],['例：けん','直しました。v2です']]},
 {id:'s16',title:'もし、農家の出荷伝票が写真で済んだら',benefit:'高齢の農家',owner:'例：りょう',age:16,stage:3,domain:'農・手続き',reframed:'もし、出荷の伝票を書かずに済んだら',first:'便益を受けるのは農家。払うのは農協か出荷組合。まず出荷組合1つで試します。',payers:['出荷組合','農協','青果卸'],lines:['伝票の様式は組合ごとに違う。1組合に限定'],build:'例：E',buy:'例：サンプル出荷組合',acc:'例：組合 事務局',actions:[['ACC','1週間分の伝票で検収',7]],bids:[['BUILD','例：E','写真→伝票の読み取りは既存部品。様式合わせが本体',30000,10,true]],criteria:['1週間分の伝票が事務局の手入力と一致する','読めなかった伝票が一覧で分かる'],deliveries:[['https://example.invalid/denpyo-v1','','例：E']]},
 // 段階4：検収（2）
 {id:'s17',title:'もし、社内の「誰に聞けばいいか」がすぐ分かったら',benefit:'入社1年目の社員',owner:'例：Dさん',age:30,stage:4,domain:'労務・社内',reframed:'もし、聞く相手が名前で出てきたら',first:'便益を受けるのは新人と総務。払うのは企業。まず1社で試します。',payers:['企業（総務）','社労士事務所','人事ソフト事業者'],lines:['社員の情報は本人の同意の範囲で'],build:'例：E',sell:'例：Dさん',buy:'例：サンプル商事',acc:'例：サンプル商事 総務',actions:[],bids:[['BUILD','例：E','業務一覧と担当者の表から検索できる形。1週間',30000,7,true]],criteria:['総務が用意した20の質問で担当者が出る','退職者が表示されない'],deliveries:[['https://example.invalid/whoto-v1','','例：E',null,true]],receipt:60000,dist:60000,distDays:2,minutes:420,ai:1200,mt:0,msgs:[['例：サンプル商事 総務','20問すべて出ました。検収します']],log:['サンプル商事 総務 が検収を確定した（段階4）','Dさん が配分案を提示した（7日間の異議期間）']},
 {id:'s18',title:'もし、地域の高齢者の見守りが新聞配達のついでにできたら',benefit:'一人暮らしの高齢者と家族',owner:'例：あき',age:28,stage:4,domain:'地域・介護',reframed:'もし、配達のついでに見守りが記録されたら',first:'便益を受けるのは家族。払うのは家族と自治体。配達員が本体。まず1販売店で試します。',payers:['家族（月額）','自治体（見守り事業）','新聞販売店'],lines:L.care,build:'例：けん',site:'例：サンプル販売店',buy:'例：家族10世帯',acc:'例：地域包括 田村',actions:[],bids:[['BUILD','例：けん','配達員がボタン1つで「異常なし」を送る形',20000,7,true],['SITE','例：サンプル販売店','配達員3人で朝の配達時に対応できる',10000,0,true]],criteria:['10世帯で2週間、毎朝の記録が残る','異常時に家族へ30分以内に届く'],deliveries:[['https://example.invalid/mimamori-v1','','例：けん',null,true]],receipt:50000,dist:50000,distDays:9,minutes:360,ai:800,mt:5000,objections:[{id:'o1',by:'例：サンプル販売店',text:'配達員の交通費5,000円が確定対価に入っていない',t:NOW-4*DAY,resolved:false}],log:['地域包括 田村 が検収を確定した（段階4）','あき が配分案を提示した（7日間の異議期間）','サンプル販売店 が配分案に異議を出した']},
 // 段階5：精算（2）
 {id:'s19',title:'もし、社員食堂の残食が翌日の献立に反映されたら',benefit:'社員食堂の運営',owner:'例：F',age:40,stage:5,domain:'食・健康経営',reframed:'もし、残った量で明日の量が決まったら',first:'便益を受けるのは食堂と会社。払うのは食堂の運営会社。廃棄の削減がそのまま原価。まず1食堂で試します。',payers:['食堂運営会社','企業（総務）','食材卸'],lines:L.food,build:'例：E',sell:'例：F',buy:'例：サンプル食堂サービス',acc:'例：サンプル食堂 店長',actions:[],bids:[['BUILD','例：E','残食の写真→量の推定→翌日の仕込み量。2週間',50000,14,true]],criteria:['2週間で廃棄量が前月比で減っている（数値は食堂が測る）','仕込み量の提案が朝8時までに出る','写真に人が写らない'],deliveries:[['https://example.invalid/zanshoku-v1','','例：E',null,true]],receipt:90000,dist:90000,distDays:12,minutes:600,ai:2000,mt:0,log:['サンプル食堂 店長 が検収を確定した（段階4）','F が配分案を提示した（7日間の異議期間）','F が模擬精算を確定した（段階5・実決済なし）']},
 {id:'s20',title:'もし、地域の空き家の「貸せるかどうか」が写真だけで分かったら',benefit:'空き家を持つ人と借りたい人',owner:'例：たかし',age:45,stage:5,domain:'地域・不動産',reframed:'もし、空き家の写真から貸せるかが分かったら',first:'便益を受けるのは所有者と自治体。払うのは自治体と不動産会社。判定より、その後の紹介が本体。まず1自治体で試します。',payers:['自治体（空き家対策）','不動産会社（紹介料）','所有者'],lines:['不動産の仲介は宅建業の免許が要る。紹介までに留める（確認）'],build:'例：けん',sell:'例：たかし',buy:'例：サンプル町役場',acc:'例：サンプル町 担当者',actions:[],bids:[['BUILD','例：けん','写真→チェックリスト→3段階の判定。10日',40000,10,true]],criteria:['30軒の写真で判定が担当者の現地確認と8割一致','判定の理由が表示される'],deliveries:[['https://example.invalid/akiya-v1','','例：けん',null,true]],receipt:80000,dist:80000,distDays:14,minutes:540,ai:1500,mt:0,log:['サンプル町 担当者 が検収を確定した（段階4）','たかし が配分案を提示した（7日間の異議期間）','たかし が模擬精算を確定した（段階5・実決済なし）']},
];
const writes=[];
for(const o of cases){ const d=base(o); if(o.stage>=5){ d.settlement={amount:o.receipt,by:o.owner,t:NOW-DAY,mock:true}; } fs.writeFileSync(path.join(OUT,o.id+'.json'),JSON.stringify(d,null,1)); writes.push({op:'set',collection:'cases',doc_id:o.id,file_path:path.join(OUT,o.id+'.json')}); }
// 精算済み案件から型を1つ（s19）
const t19=cases.find(c=>c.id==='s19');
const tpl={sourceCaseId:'s19',version:1,createdAt:NOW-DAY,by:'例：F',title:t19.title,domain:t19.domain,rephrase:'もし、残った量から翌日の仕込み量が決まったら',seats:[{role:'OWN',action:'廃棄量の測り方と達成条件を決める'},{role:'BUILD',action:'写真→量の推定→仕込み量の提案を試作'},{role:'SELL',action:'食堂運営会社に2週間の試行を提案'},{role:'ACC',action:'店長が2週間分で検収'}],criteria:t19.criteria,alloc:{fixed:45000,perf:30,idea:10,units:['u1','u2']},proposalSummary:'作る席：残食の写真から量を推定し、翌朝8時までに仕込み量を提案する試作を2週間で納品。',deliveryVersions:1,acceptedVersion:1};
fs.writeFileSync(path.join(OUT,'tpl-s19.json'),JSON.stringify(tpl,null,1)); writes.push({op:'set',collection:'templates',doc_id:'tpl-s19',file_path:path.join(OUT,'tpl-s19.json')});
fs.writeFileSync(path.join(OUT,'_writes.json'),JSON.stringify(writes,null,1));
console.log('cases',cases.length,'writes',writes.length, 'stages', cases.map(c=>c.stage).join(','));
